SET INTERPRETER=C:\Anaconda34_py36x64
SET PATH=%PATH%;%INTERPRETER%

SET WORKING_DIRECTORY=%~dp0
CD %WORKING_DIRECTORY%

SET CONFIG_DIRECTORY=%WORKING_DIRECTORY%\config_files

ECHO GRID SEARCH START IN WORKING DIRECTORY %WORKING_DIRECTORY%

REM comment: loops over and runs every config file available in the folder
for /r %%i in (.\config_files\*) do %%i

ECHO "FINISHED RUNNING GRID SEARCH, AGGREGATING RESULTS..."

python.exe .\aggregate_results.py

ECHO "RESULTS AGGREGATED, PROCESS END"